name: x-scanner 
on: [push]
env:
  RES:''

jobs:
  slack-notification-with-optional-parameters:
    runs-on: ubuntu-latest
    name: slack msg
    steps:

      - name: checkout repo
        uses: actions/checkout@v2
        env:
          RES: 'oblivion'
      - name: send message to slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.STOK_REPO }}
          slack-channel: C05E6AR5HDF 
          slack-text: ${{ env.RES }} 
          slack-optional-icon_emoji: ":red:"
